Updated the project file to add missing README.md file
microsoft/query-builder-for-digital-twins pull request #30
Opened 2022-09-01 08:45 UTC by NancyGargMS

The package's project file has been updated to include the README.md file

2022-09-06 17:18 UTC, jarz requested changes

2022-09-06 17:18 UTC, jarz commented on QueryBuilder/QueryBuilder.csproj
> +		<PackageReadmeFile>README.md</PackageReadmeFile>
Spaces, instead of tabs, please.

2022-09-06 17:18 UTC, jarz commented on QueryBuilder/QueryBuilder.csproj
> +		<None Include="..\README.md" Pack="true" PackagePath="\"/>
Spaces, instead of tabs, please.

2022-09-13 06:23 UTC, NancyGargMS commented on QueryBuilder/QueryBuilder.csproj
> +		<PackageReadmeFile>README.md</PackageReadmeFile>
Done

2022-09-13 14:15 UTC, jarz approved these changes

2022-09-15 16:33 UTC, ms-mikeb approved these changes

2022-09-16 21:33 UTC, nilay-kapadia approved these changes

2022-09-22 07:05 UTC, merged